### ISSUE TITLE
Achievement modal upgrade

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#17]
Upgrade the achievement modal so that it appears as a smaller modal on top of the screen that fades automatically. 

In doing so, also update the n-slayer achievement so that kills where you are killed count towards total kills.

**Comment by vicdjy** [comment]
Hi, 
I'm currently taking a software engineering class with a partner. We are considering probably contributing to this project by fixing. If we do, we would be looking at the 5 open issues. Before we decide on this, I wonder if we would be able to get basic support from you while reading the code and revising it? In other words, before we choose the project, we are just checking that our working process for the project would be generally smooth and wouldn't be stuck simply because of confusion on the current code base. May I also get your email address for better communication if you don't mind?

Thank you so much,
Victoria Ding

**Comment by vicdjy** [comment]
Hi, 
I'm currently taking a software engineering class with a partner. We are considering probably contributing to this project. If we do, we would be looking at fixing the 5 open issues. Before we decide on this, I wonder if we would be able to get basic support from you while reading the code and revising it? In other words, before we choose the project, we are just checking that our working process for the project would be generally smooth and wouldn't be stuck simply because of confusion on the current code base. May I also get your email address for better communication if you don't mind?
Thank you so much,
Victoria Ding

**Comment by acenturyandabit** [comment]
Hi Victoria!

I'm happy to provide basic support for reading the code. If email isn't essential however I would prefer communication via these issues to keep it professional, but if you need private communications for assignment purposes etc then let me know. I usually reply pretty quickly as you can probably see.
All the best!
Steven

**Comment by vicdjy** [comment]
Hi Steven!
Thank you so much for your prompt reply. We will be checking with the instructors tomorrow to see if working on this project would be approved for this assignment. I will let you know if the instructors approved it or not and if we could take on these open issues.

Thanks again and Best,
Victoria Ding

**Comment by vicdjy** [comment]
Hi Steve, 
In fact, we are willing to take these five issues! We would be looking at the code probably next week. We will come back to you if we have any questions.

Best,
Jiayang Ding

**Comment by dannie-zhang** [comment]
Hello Steve!

I am Victoria's partner, Dannie (Tianying). We have a quick question regarding the formatting of the code. Would it be okay for us to move the CSS and Javascript code in index.html into different files (a javascript file and a css file)? 

Thank you,
Dannie

**Comment by acenturyandabit** [comment]
Hi Dannie,

Go for it! 

Steven

**Comment by acenturyandabit** [comment]
Hey @dannie-zhang  and @vicdjy! Someone just took out the original drunk-pieces game mode (Issue #14), so I've put in issue #19 of similar difficulty to replace it. 

I'm happy to keep patching things up but if you'd like to reserve some issues please a) comment that you're reserving the issue on the issue itself, and b) let me know so I can put up more issues for others to work on.

Also, you'll need to pull those changes before you push.

All the best!
