### ISSUE TITLE
Bug: Arcade mode doesn't work if a game is forfeited prior to playing arcade mode

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#41]
Steps to reproduce:
1. Start a classic mode game.
2. Forfeit the game.
3. Start an arcade game.
Expected behavior: Arcade timer runs, game proceeds
Actual behavior: Arcade mode doesn't run.

This shouldn't be a hard bug to fix! Have a shot.

**Comment by nrademacher** [comment]
I submitted A PR :)

This is a cool little projects and I can tell ypu spend quite a bit of time making it.

However I'd strongly recommend you refactor the code and split up the logic in various separate files. This will make it much easier to debug in the future. For instance, finding a bug like this would ordinarily take just a minute or so, but since right now it's all tangled up in one big file it took me several.

**Comment by acenturyandabit** [comment]
Fixed by #42
