### ISSUE TITLE
Improved UI for picking gamemode

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#44]
Currently, to go from classic to a different game mode, you have to:
- Forfeit your current game
- NOT press the new game button
- Switch to the game mode tab
- press a button

I want that to be reduced to 1-2 steps tops, to make it easier for people to check out the other game modes.

**Comment by fengdon3** [comment]
I want contribute to this issure! This game really fascinating, I get 100 on classic mode!

**Comment by fengdon3** [comment]
I just submit the pull request, due to some reason, I may need get that pass as soon as possible QAQ. 

I implement the game mode choice UI, now they all integration on the same page with instruction so whole page look more easy to use. I also improved the appearance of the scoring, using color to distinguish them (more points can get, more rare color, same as equipment quality in diablo III, from gray to green ). And use red to enhance the present of the rules may cause difficult increase. In the end, create a forfeit button to help forfeit thus user can change game mode very quick and  clear.(press forfeit button and select new mode. 2 step)
